/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TicketTicketIdRouteImport } from './routes/ticket.$ticketId'
import { Route as OrganizerLoginRouteImport } from './routes/organizer.login'
import { Route as OrganizerDashboardRouteImport } from './routes/organizer.dashboard'
import { Route as EventEventIdRouteImport } from './routes/event.$eventId'
import { Route as OrganizerScanEventIdRouteImport } from './routes/organizer.scan.$eventId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketTicketIdRoute = TicketTicketIdRouteImport.update({
  id: '/ticket/$ticketId',
  path: '/ticket/$ticketId',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizerLoginRoute = OrganizerLoginRouteImport.update({
  id: '/organizer/login',
  path: '/organizer/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizerDashboardRoute = OrganizerDashboardRouteImport.update({
  id: '/organizer/dashboard',
  path: '/organizer/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EventEventIdRoute = EventEventIdRouteImport.update({
  id: '/event/$eventId',
  path: '/event/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizerScanEventIdRoute = OrganizerScanEventIdRouteImport.update({
  id: '/organizer/scan/$eventId',
  path: '/organizer/scan/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/event/$eventId': typeof EventEventIdRoute
  '/organizer/dashboard': typeof OrganizerDashboardRoute
  '/organizer/login': typeof OrganizerLoginRoute
  '/ticket/$ticketId': typeof TicketTicketIdRoute
  '/organizer/scan/$eventId': typeof OrganizerScanEventIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/event/$eventId': typeof EventEventIdRoute
  '/organizer/dashboard': typeof OrganizerDashboardRoute
  '/organizer/login': typeof OrganizerLoginRoute
  '/ticket/$ticketId': typeof TicketTicketIdRoute
  '/organizer/scan/$eventId': typeof OrganizerScanEventIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/event/$eventId': typeof EventEventIdRoute
  '/organizer/dashboard': typeof OrganizerDashboardRoute
  '/organizer/login': typeof OrganizerLoginRoute
  '/ticket/$ticketId': typeof TicketTicketIdRoute
  '/organizer/scan/$eventId': typeof OrganizerScanEventIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/event/$eventId'
    | '/organizer/dashboard'
    | '/organizer/login'
    | '/ticket/$ticketId'
    | '/organizer/scan/$eventId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/event/$eventId'
    | '/organizer/dashboard'
    | '/organizer/login'
    | '/ticket/$ticketId'
    | '/organizer/scan/$eventId'
  id:
    | '__root__'
    | '/'
    | '/event/$eventId'
    | '/organizer/dashboard'
    | '/organizer/login'
    | '/ticket/$ticketId'
    | '/organizer/scan/$eventId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EventEventIdRoute: typeof EventEventIdRoute
  OrganizerDashboardRoute: typeof OrganizerDashboardRoute
  OrganizerLoginRoute: typeof OrganizerLoginRoute
  TicketTicketIdRoute: typeof TicketTicketIdRoute
  OrganizerScanEventIdRoute: typeof OrganizerScanEventIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ticket/$ticketId': {
      id: '/ticket/$ticketId'
      path: '/ticket/$ticketId'
      fullPath: '/ticket/$ticketId'
      preLoaderRoute: typeof TicketTicketIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizer/login': {
      id: '/organizer/login'
      path: '/organizer/login'
      fullPath: '/organizer/login'
      preLoaderRoute: typeof OrganizerLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizer/dashboard': {
      id: '/organizer/dashboard'
      path: '/organizer/dashboard'
      fullPath: '/organizer/dashboard'
      preLoaderRoute: typeof OrganizerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event/$eventId': {
      id: '/event/$eventId'
      path: '/event/$eventId'
      fullPath: '/event/$eventId'
      preLoaderRoute: typeof EventEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizer/scan/$eventId': {
      id: '/organizer/scan/$eventId'
      path: '/organizer/scan/$eventId'
      fullPath: '/organizer/scan/$eventId'
      preLoaderRoute: typeof OrganizerScanEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EventEventIdRoute: EventEventIdRoute,
  OrganizerDashboardRoute: OrganizerDashboardRoute,
  OrganizerLoginRoute: OrganizerLoginRoute,
  TicketTicketIdRoute: TicketTicketIdRoute,
  OrganizerScanEventIdRoute: OrganizerScanEventIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
